spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

decorator:
  datasource:
    p6spy:
      enable-logging: false
